### ISSUE TITLE
About to be published sometimes shows 'live articles'

### ISSUE THREAD

**Issue by lindseydew** [guardian/about-to-be-published#5]
Our filter for removing articles that have already been published isn't always accurate. Sitting with Chris Moran we noticed a few things in the list that have already been published.

cc @chrisfinch - happy to take a look when I get a spare minute

**Comment by chrisfinch** [comment]
Alright - I'll take a look when I get time

**Comment by lindseydew** [comment]
We can see if either of us gets to it first

**Comment by lindseydew** [comment]
Have asked @clloyd to take a look at this

**Comment by lindseydew** [comment]
Closing because @clloyd fixed this
